<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/10 0010
 * Time: 22:48
 */
include "sqlSuperClass.php";
class deleteFriendClass extends sqlSuperClass {
    function deleteSql($request_user ,$receive_user){
        parent::deleteSql(); // TODO: Change the autogenerated stub
        $this->sql = "DELETE FROM friend_table WHERE request_user='{$request_user}' AND receive_user='{$receive_user}'";
        $this->conn->query($this->sql);
        $this->sql = "DELETE FROM friend_table WHERE request_user='{$receive_user}' AND receive_user='{$request_user}'";
        $this->conn->query($this->sql);
    }
}
$a = new deleteFriendClass();
$a->connectSql();
$request_user = $_GET['requestUser'];
$receive_user = $_GET['receiveUser'];
$a->deleteSql($request_user,$receive_user);
?>