<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/27 0027
 * Time: 1:47
 */
include "sqlSuperClass.php";
class ifRegisterClass extends sqlSuperClass {
    protected $userArray = array();
    public function __construct($sql){
        $this->sql = $sql;
    }

    public function querySql() {
        parent::querySql(); // TODO: Change the autogenerated stub
        $this->result = $this->getResult();
        if ($this->result->num_rows > 0) {
            while($row = $this->result->fetch_assoc()) {
                array_push($this->userArray,$row['user']);
            }
        }
    }

    public function insertSql($table,$user,$pass) {
        parent::insertSql(); // TODO: Change the autogenerated stub
        $this->setSql("insert into {$table} (user,pass) values('{$user}','{$pass}') ");
        $this->getResult();
        echo "insert_ok";
    }

    public function getUserArrary () {
        return $this->userArray;
    }


    public function returnResponse ($user,$useArray) {
        if (in_array($user,$useArray)) {
            echo "cunzai";
            return false;
        }
        return true;
    }
}
$a = new ifRegisterClass("select *from user_table");
$a->connectSql();
$a->querySql();
if ($a->returnResponse($_GET['name-user'],$a->getUserArrary())) {
    $a->insertSql("user_table",$_GET['name-user'],$_GET['name-pass']);
}
?>