<?php
/**
 * 实现需求
 * 1.查询img目录下的所有文件(jpg后缀)
 * 2.连接数据库把img的名字和URL存入数据库
 */
include "queryPhotoUrl.php";
class insertPhotoUrlClass extends queryPhotoUrlClass {
    protected $url = array();
    protected $name = array();
    protected $sqlPhotoName = array();
    public function connectFile($fileName) {
        $file = glob($fileName);//"../img/*.jpg"
        for ($i = 0; $i < count($file); $i++) {
            $len = strlen($this->name[$i])-4;
            array_push($this->url,substr($file[$i], 3));
            array_push($this->name,substr($file[$i], 7,$len));
        }
        for ($i = 0; $i < count($this->name); $i++) {
            if (in_array($this->name[$i],$this->sqlPhotoName)) {

            }else {
                $this->insertSql("photo_table",['photo_name','photo_url'],[$this->name[$i],$this->url[$i]],false);
            }
        }
    }
    public function querySql(){
        parent::querySql(); // TODO: Change the autogenerated stub
        $this->sql = "select photo_name from photo_table";
        $this->result = $this->getResult();
        if ($this->result->num_rows > 0) {
            while($row = $this->result->fetch_assoc()) {
                array_push($this->sqlPhotoName,$row['photo_name']);
            }
        }
    }
}
$a = new insertPhotoUrlClass();
$a->connectSql();
$a->querySql();
$a->connectFile('../img/*.jpg');
$a->jumpPHP("queryPhotoUrl.php");

?>