<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/18 0018
 * Time: 2:03*/

include "sqlSuperClass.php";
class insertFriendClass extends sqlSuperClass {
    function deleteSql($request_user ,$receive_user){
        parent::deleteSql(); // TODO: Change the autogenerated stub
        $this->sql = "DELETE FROM friend_table WHERE request_user='{$request_user}' AND receive_user='{$receive_user}'";
        $this->conn->query($this->sql);
    }
}
$a = new insertFriendClass();
$a->connectSql();
$request_user = $_GET['requestUser'];
$receive_user = $_GET['receiveUser'];
$a->deleteSql($request_user,$receive_user);
if ($request_user == null || $receive_user == null) {

}else {
    $a->insertSql('friend_table',['request_user','request_state','receive_user','receive_state'],[$request_user,2,$receive_user,1],false);
    echo "ok";
}


?>