<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/7 0007
 * Time: 19:15
 */
include_once "sqlSuperClass.php";
class queryFriendListClass extends sqlSuperClass {
    protected $sqlRequestUser = array();
    protected $sqlRequestState = array();
    protected $sqlReceiveUser = array();
    protected $sqlReceiveState = array();
    //要传输到前端的好友列表
    protected $friendList = array();
    public function querySql(){
        parent::querySql(); // TODO: Change the autogenerated stub
        $this->sql = "SELECT *FROM friend_table";
        $this->result = $this->getResult();
        if ($this->result->num_rows > 0) {
            while($row = $this->result->fetch_assoc()) {
                array_push($this->sqlRequestUser,$row['request_user']);
                array_push($this->sqlRequestState,$row['request_state']);
                array_push($this->sqlReceiveUser,$row['receive_user']);
                array_push($this->sqlReceiveState,$row['receive_state']);
            }
        }
    }
    public function getFriendList($user) {
        //array_push($this->friendList,$this->sqlRequestUser[$i]);
        for ($i = 0; $i < count($this->sqlRequestUser); $i++) {
            if ($this->sqlRequestUser[$i] == $user) {
                if ($this->sqlRequestState[$i] == 2 && $this->sqlReceiveState[$i] == 2) {
                    array_push($this->friendList,$this->sqlReceiveUser[$i]);
                }
            }
            if ($this->sqlReceiveUser[$i] == $user) {
                if ($this->sqlRequestState[$i] == 2 && $this->sqlReceiveState[$i] == 2) {
                    array_push($this->friendList,$this->sqlRequestUser[$i]);
                }
            }
        }
        return $this->friendList;
    }
}
$a = new queryFriendListClass();
$a->connectSql();
$a->querySql();
echo json_encode($a->getFriendList($_GET['user']));
?>