<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/24 0024
 * Time: 0:34
 */
session_start();
include "sqlSuperClass.php";
include "printXmlMethond.php";
include "ifSessionState.php";

class queryCommentClass extends sqlSuperClass {
    protected $userArray = array();
    protected $commentArray = array();
    protected $dateArray = array();
    protected $id = array();
    protected $xmlElement = array();


    public function __construct($sql,$xmlElement) {
        $this->sql = $sql;
        $this->xmlElement = $xmlElement;
    }

    public function querySql() {
        parent::querySql(); // TODO: Change the autogenerated stub
        $this->result = $this->getResult();
        if ($this->result->num_rows > 0) {
            while($row = $this->result->fetch_assoc()) {
                array_push($this->userArray,$row[$this->xmlElement[0]]);
                array_push($this->commentArray,$row[$this->xmlElement[1]]);
                array_push($this->dateArray,$row[$this->xmlElement[2]]);
                array_push($this->id,$row[$this->xmlElement[3]]);
            }
        }
    }

    public function getUserArray() {
        return $this->userArray;
    }

    public function getCommentArray() {
        return $this->commentArray;
    }

    public function getDateArray() {
        return $this->dateArray;
    }

    public function getXmlElement() {
        return $this->xmlElement;
    }

    public function getId() {
        return $this->id;
    }
}

$a = new queryCommentClass('select* from comment',array("user","text","date","id"));
$a->connectSql();
$a->querySql();
printXmlMethond("blogCommentXml.xml","commentSql","commentPro",$a->getUserArray(),$a->getCommentArray(),$a->getdateArray(),$a->getId(),$a->getXmlElement());
if (ifSeesionState()) {
    $a->jumpPHP('../indexMoreComment.php');
}else {
    $a->jumpPHP('../indexBackStage.php');
}

?>