<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/24 0024
 * Time: 21:57
 */
include "sqlSuperClass.php";
include "printXmlMethond.php";

class queryBookClass extends sqlSuperClass {
    protected $nameArray = array();
    protected $urlArray = array();
    protected $idArray = array();
    protected $xmlElement = array();

    public function __construct($sql,$xmlElement) {
        $this->sql = $sql;
        $this->xmlElement = $xmlElement;
    }

    public function querySql() {
        parent::querySql(); // TODO: Change the autogenerated stub
        $this->result = $this->getResult();
        if ($this->result->num_rows > 0) {
            while($row = $this->result->fetch_assoc()) {
                array_push($this->nameArray,$row[$this->xmlElement[0]]);
                array_push($this->urlArray,$row[$this->xmlElement[1]]);
                array_push($this->idArray,$row[$this->xmlElement[2]]);
            }
        }
    }

    public function getNameArray() {
        return $this->nameArray;
    }

    public function getUrlArray() {
        return $this->urlArray;
    }

    public function getIdArray() {
        return $this->idArray;
    }

    public function getXmlElement() {
        return $this->xmlElement;
    }
}
$a = new queryBookClass("select *from book_table",array('name','url','id'));
$a->connectSql();
$a->querySql();
printXmlMethond("blogBookXml.xml","bookSql","bookPro",$a->getNameArray(),$a->getUrlArray(),$a->getIdArray(),$a->getXmlElement());
$a->jumpIndex();
?>